config/routes.rb
Rails.application.routes.draw do

  root "tasks#index"
  resources :tasks do
    resources :realizations
    member do
      get 'mark_as_done'
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/realization.rb
class Realization < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :deadline, presence: true
  has_many :realizations, dependent: :destroy


  scope :upcoming_deadline, -> { where('deadline > ?', Time.zone.now).order('deadline ASC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy mark_as_done ]

  def index
    @tasks = Task.upcoming_deadline
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    result = CreateTask.new(params).call


    if result.success?
      redirect_to tasks_url, notice: 'Task successfully created'
    else
      flash.now[:alert] = result.failure
      render :new
    end
  end

  def update

    result = UpdateTask.new(@task, params).call

    if result.success?
      redirect_to root_path, notice: 'Task was successfully updated'
    else
      flash.now[:alert] = result.failure
      render :edit
    end
  end

  def destroy
    result = DeleteTask.new(@task).call

    if result.success?
      redirect_to tasks_url, notice: 'Task successfully destroyed'
    else
      flash.now[:alert] = result.failure
      render :edit
    end

  end

  def mark_as_done
    @task.realizations.create(done_at: Time.zone.now)
    redirect_back fallback_location: root_path, notice: 'Task Finished - well  done.'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warsztaty inFakt 2023 - TO-DO list</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <%= content_tag :div, class: "alert alert-info", id: "notice" do -%>
              <%= notice %>
            <% end if notice.present? -%>

            <% if @task.errors.any? %>
              <% @task.errors.full_messages.each do |message| %>
                <%= content_tag :div, class: "alert alert-danger", role: 'alert' do -%>
                  <%= message %>
                <% end -%>
              <% end %>
            <% end %>

            <h4 class="text-center my-3 pb-3">To Do App</h4>
            <div class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
              <%= button_to "Tasks list", tasks_path, method: :get, class: "btn btn-primary" %>
            </div>

            <%= form_with(model: @task) do |form| %>
              <div>
                <%= form.label :title, style: "display: block" %>
                <%= form.text_field :title %>
              </div>

              <div>
                <%= form.label :description, style: "display: block" %>
                <%= form.text_area :description %>
              </div>

              <div>
                <%= form.label :deadline, style: "display: block" %>
                <%= form.date_select :deadline, { order: [:year, :month, :day], start_year: Date.today.year, end_year: Date.today.year + 1 } %>
              </div>

              <div>
                <%= form.submit %>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tasks/index.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container py- h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-12">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <%= content_tag :div, class: "alert alert-info", id: "notice" do -%>
              <%= notice %>
            <% end if notice.present? -%>

            <h4 class="text-center my-3 pb-3">To Do App</h4>
            <div class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
              <%= button_to "New task", new_task_path, method: :get, class: "btn btn-primary" %>
            </div>

            <table class="table mb-6">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Title</th>
                  <th scope="col">Description</th>
                  <th scope="col">Deadline</th>
                  <th scope="col">Finished</th>
                </tr>
              </thead>
              <tbody>
              <% counter = 1 %>
                <% @tasks.each do |task| %>
                  <tr>
                    <th scope="row"><%= counter %></th>
                    <td><%= task.title %></td>
                    <td><%= task.description %></td>
                    <td><%= task.deadline.strftime('%Y-%m-%d')  %></td>
                    <td><%= task.realizations.last&.done_at&.strftime('%Y-%m-%d') %></td>
                    <td class="actions">
                       <td><%= link_to 'Finish', mark_as_done_task_path(task),class:  "btn btn-info" %>  </td>
                       <td><%= link_to "Show", task, class: "btn btn-success" %></td>
                       <td><%= link_to 'Edit', edit_task_path(task), class: "btn btn-primary" %></td>
                       <td><%= button_to "Delete", task, method: :delete, class: "btn btn-danger" %></td>
                    </td>
                  </tr>
                 <% counter += 1 %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tasks/new.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <%= content_tag :div, class: "alert alert-info", id: "notice" do -%>
              <%= notice %>
            <% end if notice.present? -%>

            <% if @task.errors.any? %>
              <% @task.errors.full_messages.each do |message| %>
                <%= content_tag :div, class: "alert alert-danger", role: 'alert' do -%>
                  <%= message %>
                <% end -%>
              <% end %>
            <% end %>

            <h4 class="text-center my-3 pb-3">To Do App</h4>
            <div class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
              <%= button_to "Tasks list", tasks_path, method: :get, class: "btn btn-primary" %>
            </div>

            <%= form_with(model: @task) do |form| %>
              <div>
                <%= form.label :title, style: "display: block" %>
                <%= form.text_field :title %>
              </div>

              <div>
                <%= form.label :description, style: "display: block" %>
                <%= form.text_area :description %>
              </div>

              <div>
                <%= form.label :deadline, style: "display: block" %>
                <%= form.date_select :deadline, { order: [:year, :month, :day], start_year: Date.today.year, end_year: Date.today.year + 1 } %>
              </div>

              <div>
                <%= form.submit %>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tasks/show.html.erb
<section class="vh-100" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card rounded-3">
          <div class="card-body p-4">

            <%= content_tag :div, class: "alert alert-info", id: "notice" do -%>
              <%= notice %>
            <% end if notice.present? -%>

            <% if @task.errors.any? %>
              <% @task.errors.full_messages.each do |message| %>
                <%= content_tag :div, class: "alert alert-danger", role: 'alert' do -%>
                  <%= message %>
                <% end -%>
              <% end %>
            <% end %>

            <h4 class="text-center my-3 pb-3">To Do App</h4>
            <div class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2">
              <%= button_to "Tasks list", tasks_path, method: :get, class: "btn btn-primary" %>
            </div>

            <p>
              <strong>Title:</strong>
              <%= @task.title %>
            </p>
            <p>
              <strong>Description:</strong>
              <%= @task.description %>
            </p>
            <p>
              <strong>Deadline:</strong>
              <%= @task.deadline.strftime('%Y-%m-%d') %>
            </p>

            <p>
              <strong>Finish:</strong>
              <%= @task.realizations.last&.done_at&.strftime('%Y-%m-%d')  %>
            </p>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>